version: "3.7"

services:
  qdrant-node-0:
    image: qdrant/qdrant:${QDRANT_VERSION:-v1.11.0}
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    ports:
      - "6333:6333"
      - "6334:6334"
    command: ./qdrant --uri 'http://qdrant-node-0:6335'
#    deploy:
#      resources:
#        limits:
#          cpus: '0.07'


  qdrant-node-1:
    image: qdrant/qdrant:${QDRANT_VERSION:-v1.11.0}
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    depends_on:
      - qdrant-node-0
    ports:
      - "6433:6333"
      - "6434:6334"
    command: bash -c "sleep 5 && ./qdrant --bootstrap 'http://qdrant-node-0:6335' --uri 'http://qdrant-node-1:6335'"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.05'


  qdrant-node-2:
    image: qdrant/qdrant:${QDRANT_VERSION:-v1.11.0}
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    depends_on:
      - qdrant-node-0
    ports:
      - "6533:6333"
      - "6534:6334"
    command: bash -c "sleep 6 && ./qdrant --bootstrap 'http://qdrant-node-0:6335' --uri 'http://qdrant-node-2:6335'"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.03'
