[tool.poetry]
name = "vector-db-benchmark"
version = "0.1.0"
description = ""
authors = ["Qdrant Team <info@qdrant.tech>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
qdrant-client = { git = "https://github.com/qdrant/qdrant-client.git", branch = "dev" }
typer = "^0.27.1"
jsons = "^1.6.3"
h5py = "^3.7.0"
weaviate-client = ">=4.23.0,<4.24"
elasticsearch = "^9.5.0"
pymilvus = "^2.5.0"
redis = "^5.0.1"
ipdb = "^0.13.9"
opensearch-py = "^3.2.0"
tqdm = "^4.70.0"
psycopg = {extras = ["binary"], version = "^3.1.17"}
pgvector = "^0.5.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.6.2"
pytest = "^9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
