name: Run Engine Benchmark
description: "Run benchmark with specified params"
inputs:
  engine:
    description: "engine (i.e qdrant-default)"
    required: true
  dataset:
    description: "dataset (i.e random-100)"
    required: true
  compose_file:
    description: "path to docker compose"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pip install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install deps
      shell: bash
      run: poetry install
    - uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: "${{ inputs.compose_file }}"
    - name: Execution
      shell: bash
      run: |
        engine="${{ inputs.engine }}"
        if [[ "$engine" == *"elasticsearch"* || "$engine" == *"opensearch"* ]]; then
          ./tools/wait_for_green_status.sh
        fi
        source $(poetry env info -p)/bin/activate
        poetry run python3 run.py --engines "${{ inputs.engine }}" --datasets "${{ inputs.dataset }}"