version: '3.5'

services:
  opensearch:
    image: opensearchproject/opensearch:2.17.1
    environment:
      discovery.type: "single-node"
      DISABLE_SECURITY_PLUGIN: true
      DISABLE_INSTALL_DEMO_CONFIG: true
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 4Gb
