name: 'Create Server with Retry'
description: 'Create a Hetzner server with retry logic'
inputs:
  server_name:
    description: 'Name of the server to create'
    required: true
  server_type:
    description: 'Type of server to create'
    required: true
  region:
    description: 'Region to create the server in'
    required: false
    default: 'fsn1'
  max_retries:
    description: 'Maximum number of retry attempts'
    required: false
    default: '5'
outputs:
  success:
    description: 'Whether the server was created successfully'
    value: ${{ steps.create.outputs.success }}
runs:
  using: "composite"
  steps:
    - name: Create server with retries
      id: create
      shell: bash
      run: |
        SERVER_NAME="${{ inputs.server_name }}"
        SERVER_TYPE="${{ inputs.server_type }}"
        MAX_RETRIES="${{ inputs.max_retries }}"
        SERVER_LOCATION="${{ inputs.region }}"
        RETRY_COUNT=0

        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "Creating server $SERVER_NAME (attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)..."

          if SERVER_NAME=$SERVER_NAME SERVER_TYPE=$SERVER_TYPE SERVER_LOCATION=$SERVER_LOCATION bash -x "tools/hetzner/create_and_install.sh"; then
            echo "Successfully created server $SERVER_NAME"
            echo "success=true" >> $GITHUB_OUTPUT
            exit 0
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "Failed to create server $SERVER_NAME, waiting 60 seconds before retry..."
              sleep 60
            fi
          fi
        done

        echo "Failed to create server $SERVER_NAME after $MAX_RETRIES attempts"
        echo "success=false" >> $GITHUB_OUTPUT
        exit 1