version: '3.7'

services:
  qdrant_bench:
    image: ${CONTAINER_REGISTRY:-docker.io}/qdrant/qdrant:${QDRANT_VERSION}
    container_name: qdrant-continuous
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: ${CONTAINER_MEM_LIMIT:-25Gb}

volumes:
  qdrant_storage:
    name: "qdrant_storage"
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/qdrant_storage
      o: bind
