qdrant_python_client_version: "1.14.0"
logging_dir: "/tmp/logs"
working_dir: "/tmp/experiments"
# Defaults (can be overridden via --extra-vars)
dataset_name: "dbpedia_openai_100K"
points_percentages:
  - "1"
  - "2"
  - "5"
  - "10"
  - "15"
  - "20"
  - "25"
  - "30"
  - "40"
  - "50"
servers:
  - name: "qdrant"
    registry: "ghcr.io"
    image: "qdrant/qdrant"
    version: "dev"
    feature_flags: "true"
  - name: "qdrant"
    registry: "docker.io"
    image: "qdrant/qdrant"
    version: "master"
    feature_flags: "false"
