qdrant_python_client_version: "1.14.0"
logging_dir: "/tmp/logs"
working_dir: "/tmp/experiments"
dataset_url: "https://storage.googleapis.com/ann-filtered-benchmark/datasets/cohere-wiki-100k-no-filters.tgz"
dataset_name: "cohere-wiki-100k-no-filters"
dataset_dim: "768"
dataset_2_url: "https://storage.googleapis.com/ann-filtered-benchmark/datasets/cohere-wiki-100k-no-filters-2.tgz"
dataset_2_name: "cohere-wiki-100k-no-filters-2"
servers:
  - name: "qdrant"
    registry: "ghcr.io"
    image: "qdrant/qdrant"
    version: "dev"
    feature_flags: "true"
  - name: "qdrant"
    registry: "docker.io"
    image: "qdrant/qdrant"
    version: "master"
    feature_flags: "false"
