qdrant_python_client_version: "1.14.0"
logging_dir: "/tmp/logs"
working_dir: "/tmp/experiments"
# Default dataset values (can be overridden via --extra-vars)
dataset_name: "laion-small-clip-no-filters-1"
dataset_2_name: "laion-small-clip-no-filters-2"
servers:
  - name: "qdrant"
    registry: "ghcr.io"
    image: "qdrant/qdrant"
    version: "dev"
    feature_flags: "true"
  - name: "qdrant"
    registry: "docker.io"
    image: "qdrant/qdrant"
    version: "master"
    feature_flags: "false"
