version: '3.7'

services:
  qdrant_bench:
    image: qdrant/qdrant:${QDRANT_VERSION:-v1.11.0}
    ports:
      - "6333:6333"
      - "6334:6334"
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 2Gb
