name: Manual All Engines Default Benchmarks

on:
  push:
    branches:
     - "master"
  pull_request:
    types:
      - opened
      - reopened
      - edited
  workflow_dispatch:

jobs:
  checkChanges:
    name: check this
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            weaviate:
              - 'engine/clients/weaviate/**'
              - 'engine/servers/weaviate-single-node/**'
              - 'engine/base_client/**'
      - name: see me
        run: |
          echo "${{ steps.changes.outputs.weaviate == 'true' }} || ${{ github.event_name == 'workflow_dispatch' }}"
          echo "${{ steps.changes.outputs.weaviate }}"
          echo "${{ steps.changes.outputs.weaviate == 'true' }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event_name == 'workflow_dispatch' }}"
      - name: see me if manual
        if: ( ${{ steps.changes.outputs.weaviate == 'true' }} || ${{ github.event_name == 'workflow_dispatch' }} )
        run: |
          echo "${{ steps.changes.outputs.weaviate == 'true' }} || ${{ github.event_name == 'workflow_dispatch' }}"
          echo "${{ steps.changes.outputs.weaviate }}"
          echo "${{ steps.changes.outputs.weaviate == 'true' }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event_name == 'workflow_dispatch' }}"