name: Manual All Engines Default Benchmarks

on:
  push:
    branches:
     - "master"
  pull_request:
    types:
      - opened
      - reopened
      - edited
  workflow_dispatch:

jobs:
  checkChanges:
    name: check this
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            weaviate:
              - 'engine/clients/weaviate/**'
              - 'engine/servers/weaviate-single-node/**'
              - 'engine/base_client/**'
      - name: see me
        run: |
          echo "${{ steps.changes.outputs.weaviate }}"
          echo ""
          echo "${{ github.event_name }}"
          echo "${{ github.event_name == 'workflow_dispatch' }}"