name: Manual All Engines Default Benchmarks

on:
  push:
    branches:
     - "ci/benchmark-all-engines"
  workflow_dispatch:

jobs:
  elasticsearchBenchmark:
    name: benchmark - elasticsearch-default - random-100 - against elasticsearch-single-node-ci
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install --no-root

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/elasticsearch-single-node-ci/docker-compose.yaml"
      - name: Execution
        run: |
          ./tools/wait_for_green_status.sh
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "elasticsearch-default" --datasets "random-100"

  milvusBenchmark:
    name: benchmark - milvus-default - random-100 - against milvus-single-node
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/milvus-single-node/docker-compose.yaml"
      - name: Execution
        run: |
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "milvus-default" --datasets "random-100"

  opensearchBenchmark:
    name: benchmark - opensearch-default - glove-25-angular - against opensearch-single-node-ci
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/opensearch-single-node-ci/docker-compose.yaml"
      - name: Execution
        run: |
          ./tools/wait_for_green_status.sh
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "opensearch-default" --datasets "glove-25-angular"  

  pgvectorBenchmark:
    name: benchmark - pgvector-default - random-100 - against pgvector-single-node
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/pgvector-single-node/docker-compose.yaml"
      - name: Execution
        run: |
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "pgvector-default" --datasets "random-100" 

  qdrantBenchmark:
    name: benchmark - qdrant-default - random-100 - against qdrant-single-node
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/qdrant-single-node/docker-compose.yaml"
      - name: Execution
        run: |
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "qdrant-default" --datasets "random-100" 

  redisBenchmark:
    name: benchmark - redis-default - random-100 - against redis-single-node
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/redis-single-node/docker-compose.yaml"
      - name: Execution
        run: |
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "redis-default" --datasets "random-100" 

  weaviateBenchmark:
    name: benchmark - weaviate-default - random-100 - against weaviate-single-node
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install deps
        run: poetry install

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "engine/servers/weaviate-single-node/docker-compose.yaml"
      - name: Execution
        run: |
          source $(poetry env info -p)/bin/activate
          poetry run python3 run.py --engines "weaviate-default" --datasets "random-100"